# This [YAML](http://www.yaml.org/spec/1.2/spec.html#id2761803) configures
# the normalizationa of inputs, their relation to channels and styles to be
# used for drawing histograms.
#
# Each MC sample is called **Input**, e.g.:
#
#   stop-s, stop-t, wjets, zjet
#
# Inputs are groupped into **Channel**s, e.g.:
#
#   stop-s, stop-t, stop-tw, etc.           -> stop
#   ttbar                                   -> ttbar
#
# Each input plot is automatically scaled with luminosity, corresponding
# cross-section and number of events. These numbers are defined in the config
# below
#
# Warning: use unique names in inputs. The same is applied to channels
#
# ------------------------------------------------------------------------------
#
# ROOT Color Constants: used for back reference in YAML and NOT used in the code
#
color:
    # Get colors from ROOT in interactive session:
    # root [0] kRed
    # (const enum EColor)632
    #
    black: &black 1
    red: &red 632
    blue: &blue 600
    green: &green 416
    magenta: &magenta 616
    yellow: &yellow 400
    azure: &azure 860
    gray: &gray 920
    orange: &orange 800 

# Luminosity in [pb-1]
luminosity: 19632 
# Collition energy in [TeV]
energy: 8 

# Each input is defined by its name, number of processed events, and
# cross-sectionb. Each input can be turned ON or OFF from loading.
#
input:
    # SM ttbar
    #     
    - name: MC.TTbar
      events: null
      xsection: null
      enable: True
    - name: MC.TTbar_0to700
      events: null
      xsection: null
      enable: True
    - name: MC.TTbar_700to1000
      events: null
      xsection: null
      enable: True
    - name: MC.TTbar_1000toInf
      events: null
      xsection: null
      enable: True
    # Z + jets
    #
    - name: MC.DYJets_10to50
      events: null
      xsection: null
      enable: True
    - name: MC.DYJets_50toInf 
      events: null
      xsection: null
      enable: True
    - name: MC.DY1Jets_50toInf 
      events: null
      xsection: null
      enable: True
    - name: MC.DY2Jets_50toInf
      events: null
      xsection: null
      enable: True
    - name: MC.DY3Jets_50toInf
      events: null
      xsection: null
      enable: True
    - name: MC.DY4Jets_50toInf
      events: null
      xsection: null
      enable: True
    - name: MC.DYJets_10to50_BFlavor
      events: null
      xsection: null
      enable: True
    - name: MC.DYJets_50toInf_BFlavor
      events: null
      xsection: null
      enable: True
    - name: MC.DY1Jets_50toInf_BFlavor
      events: null
      xsection: null
      enable: True
    - name: MC.DY2Jets_50toInf_BFlavor
      events: null
      xsection: null
      enable: True
    - name: MC.DY3Jets_50toInf_BFlavor
      events: null
      xsection: null
      enable: True
    - name: MC.DY4Jets_50toInf_BFlavor
      events: null
      xsection: null
      enable: True
    - name: MC.DYJets_10to50_CFlavor
      events: null
      xsection: null
      enable: True
    - name: MC.DYJets_50toInf_CFlavor
      events: null
      xsection: null
      enable: True
    - name: MC.DY1Jets_50toInf_CFlavor
      events: null
      xsection: null
      enable: True
    - name: MC.DY2Jets_50toInf_CFlavor
      events: null
      xsection: null
      enable: True
    - name: MC.DY3Jets_50toInf_CFlavor
      events: null
      xsection: null
      enable: True
    - name: MC.DY4Jets_50toInf_CFlavor
      events: null
      xsection: null
      enable: True
    - name: MC.DYJets_10to50_LFlavor
      events: null
      xsection: null
      enable: True
    - name: MC.DYJets_50toInf_LFlavor
      events: null
      xsection: null
      enable: True
    - name: MC.DY1Jets_50toInf_LFlavor
      events: null
      xsection: null
      enable: True
    - name: MC.DY2Jets_50toInf_LFlavor
      events: null
      xsection: null
      enable: True
    - name: MC.DY3Jets_50toInf_LFlavor
      events: null
      xsection: null
      enable: True
    - name: MC.DY4Jets_50toInf_LFlavor
      events: null
      xsection: null
      enable: True
    # W + jets
    #
    - name: MC.WJets
      events: null
      xsection: null
      enable: True
    - name: MC.W1Jets
      events: null
      xsection: null
      enable: True
    - name: MC.W2Jets
      events: null
      xsection: null
      enable: True
    - name: MC.W3Jets
      events: null
      xsection: null
      enable: True
    - name: MC.W4Jets
      events: null
      xsection: null
      enable: True

    - name: MC.WJets_BFlavor
      events: null
      xsection: null
      enable: True
    - name: MC.W1Jets_BFlavor
      events: null
      xsection: null
      enable: True
    - name: MC.W2Jets_BFlavor
      events: null
      xsection: null
      enable: True
    - name: MC.W3Jets_BFlavor
      events: null
      xsection: null
      enable: True
    - name: MC.W4Jets_BFlavor
      events: null
      xsection: null
      enable: True
    - name: MC.WJets_CFlavor
      events: null
      xsection: null
      enable: True
    - name: MC.W1Jets_CFlavor
      events: null
      xsection: null
      enable: True
    - name: MC.W2Jets_CFlavor
      events: null
      xsection: null
      enable: True
    - name: MC.W3Jets_CFlavor
      events: null
      xsection: null
      enable: True
    - name: MC.W4Jets_CFlavor
      events: null
      xsection: null
      enable: True
    - name: MC.WJets_LFlavor
      events: null
      xsection: null
      enable: True
    - name: MC.W1Jets_LFlavor
      events: null
      xsection: null
      enable: True
    - name: MC.W2Jets_LFlavor
      events: null
      xsection: null
      enable: True
    - name: MC.W3Jets_LFlavor
      events: null
      xsection: null
      enable: True
    - name: MC.W4Jets_LFlavor
      events: null
      xsection: null
      enable: True
    # Single-top(s)
    #
    - name: MC.SingleTop_T_sch 
      events: null
      xsection: null
      enable: True
    - name: MC.SingleTop_T_tch
      events: null
      xsection: null
      enable: True
    - name: MC.SingleTop_T_tWch
      events: null
      xsection: null
      enable: True
    - name: MC.SingleTop_Tbar_sch
      events: null
      xsection: null
      enable: True
    - name: MC.SingleTop_Tbar_tch
      events: null
      xsection: null
      enable: True
    - name: MC.SingleTop_Tbar_tWch
      events: null
      xsection: null
      enable: True
    # Diboson
    #
    - name: MC.WW 
      events: null
      xsection: null
      enable: True
    - name: MC.ZZ
      events: null
      xsection: null
      enable: True
    # QCD
    #
    - name: MC.QCD_Pt_20_30_BCtoE
      events: null
      xsection: null
      enable: True
    - name: MC.QCD_Pt_30_80_BCtoE
      events: null
      xsection: null
      enable: True
    - name: MC.QCD_Pt_80_170_BCtoE
      events: null
      xsection: null
      enable: True
    - name: MC.QCD_Pt_170_250_BCtoE
      events: null
      xsection: null
      enable: True
    - name: MC.QCD_Pt_350_BCtoE
      events: null
      xsection: null
      enable: True
    - name: MC.QCD_Pt_20_30_EMEnriched
      events: null
      xsection: null
      enable: True
    - name: MC.QCD_Pt_30_80_EMEnriched
      events: null
      xsection: null
      enable: True
    - name: MC.QCD_Pt_80_170_EMEnriched
      events: null
      xsection: null
      enable: True
    - name: MC.QCD_Pt_170_250_EMEnriched
      events: null
      xsection: null
      enable: True
    - name: MC.QCD_Pt_250_350_EMEnriched
      events: null
      xsection: null
      enable: True
    - name: MC.QCD_Pt_350_EMEnriched
      events: null
      xsection: null
      enable: True
    # Signals
    #
    - name: MC.ZP500w5
      events: null
      xsection: null
      enable: True
    - name: MC.ZP750w7p5
      events: null
      xsection: null
      enable: True
    - name: MC.ZP1000w10
      events: null
      xsection: null
      enable: True
    - name: MC.ZP1250w12p5
      events: null
      xsection: null
      enable: True
    - name: MC.ZP1500w15
      events: null
      xsection: null
      enable: True
    - name: MC.ZP2000w20
      events: null
      xsection: null
      enable: True
    - name: MC.ZP3000w30
      events: null
      xsection: null
      enable: True
    - name: MC.ZP4000w40
      events: null
      xsection: null
      enable: True
    - name: MC.ZP500w50
      events: null
      xsection: null
      enable: True
    - name: MC.ZP750w75
      events: null
      xsection: null
      enable: True
    - name: MC.ZP1000w100
      events: null
      xsection: null
      enable: True
    - name: MC.ZP1250w125
      events: null
      xsection: null
      enable: True
    - name: MC.ZP1500w150
      events: null
      xsection: null
      enable: True
    - name: MC.ZP2000w200
      events: null
      xsection: null
      enable: True
    - name: MC.ZP3000w300
      events: null
      xsection: null
      enable: True
    - name: MC.ZP4000w400
      events: null
      xsection: null
      enable: True
    - name: MC.RSG1000
      events: null
      xsection: null
      enable: True
    - name: MC.RSG1500
      events: null
      xsection: null
      enable: True
    - name: MC.RSG2000
      events: null
      xsection: null
      enable: True
    - name: MC.RSG3000
      events: null
      xsection: null
      enable: True
    - name: MC.RSG3500
      events: null
      xsection: null
      enable: True
    - name: MC.RSG4000
      events: null
      xsection: null
      enable: True
    # Data samples
    #
    - name: DATA.DATA
      events: null
      xsection: null
      enable: True
    # Data-driven qcd sample
    #  
    - name: DATA.QCD
      events: null
      xsection: null
      enable: True
# Define policy on how inputs can be grouped into channels
#
channel:
    # Define how inputs can be grouped into channels
    # color is specified by [base, shift] 
    - name: ttbar
      inputs: [MC.TTbar_0to700, MC.TTbar_700to1000, MC.TTbar_1000toInf]
      # inputs: [MC.TTbar]
      legend: !!str "t#bar{t}"
      color: [*red, -3]
      fill: True
      line: null
    - name: wjets
      inputs: [MC.W1Jets, MC.W2Jets, MC.W3Jets, MC.W4Jets]
      # inputs: [MC.WJets]
      legend: !!str "W#rightarrowl#nu"
      color: [*green, -3]
      fill: True
      line: null
    - name: wb
      inputs: [MC.W1Jets_BFlavor, MC.W2Jets_BFlavor, MC.W3Jets_BFlavor, MC.W4Jets_BFlavor]
      #inputs: [MC.WJets_BFlavor]
      legend: !!str "W#rightarrowl#nu (+b)"
      color: [*green, -1]
      fill: True
      line: null
    - name: wc
      inputs: [MC.W1Jets_CFlavor, MC.W2Jets_CFlavor, MC.W3Jets_CFlavor, MC.W4Jets_CFlavor]
      #inputs: [MC.WJets_CFlavor]
      legend: !!str "W#rightarrowl#nu (+c)"
      color: [*green, -2]
      fill: True
      line: null
    - name: wlight
      inputs: [MC.W1Jets_LFlavor, MC.W2Jets_LFlavor, MC.W3Jets_LFlavor, MC.W4Jets_LFlavor]
      #inputs: [MC.WJets_LFlavor]
      legend: !!str "W#rightarrowl#nu (+light)"
      color: [*green, -3]
      fill: True
      line: null
    - name: zjets
      #inputs: [MC.DYJets_10to50, MC.DY1Jets_50toInf, MC.DY2Jets_50toInf, MC.DY3Jets_50toInf, MC.DY4Jets_50toInf]
      inputs: [MC.DY1Jets_50toInf, MC.DY2Jets_50toInf, MC.DY3Jets_50toInf, MC.DY4Jets_50toInf]
      #inputs: [MC.DYJets_10to50, MC.DYJets_50toInf]
      legend: !!str "Z/#gamma*#rightarrowl^{+}l^{-}"
      color: [*azure, -2]
      fill: True
      line: null
    - name: stop
      inputs: [MC.SingleTop_T_sch, MC.SingleTop_T_tch, MC.SingleTop_T_tWch, MC.SingleTop_Tbar_sch, MC.SingleTop_Tbar_tch, MC.SingleTop_Tbar_tWch]
      legend: !!str "Single-Top"
      color: [*magenta, 0]
      fill: True
      line: null
    - name: diboson
      inputs: [MC.WW, MC.ZZ]
      legend: !!str "Diboson"
      color: [*orange, -3]
      fill: True
      line: null
    - name: qcd
      inputs: [MC.QCD_Pt_20_30_BCtoE, MC.QCD_Pt_30_80_BCtoE, MC.QCD_Pt_80_170_BCtoE, MC.QCD_Pt_170_250_BCtoE, MC.QCD_Pt_350_BCtoE,  MC.QCD_Pt_20_30_EMEnriched,  MC.QCD_Pt_30_80_EMEnriched,  MC.QCD_Pt_80_170_EMEnriched,  MC.QCD_Pt_170_250_EMEnriched,  MC.QCD_Pt_250_350_EMEnriched,  MC.QCD_Pt_350_EMEnriched]
      legend: !!str "MC QCD"
      color: [*yellow, 1] 
      fill: True
      line: null
    #
    #
    - name: zp500w5
      inputs: [MC.ZP500w5]
      legend: !!str "Z' 0.50 TeV/c^{2} (1%)"
      color: [*gray, 3]
      fill: False
      line: 1
    - name: zp750w7p5
      inputs: [MC.ZP750w7p5]
      legend: !!str "Z' 0.75 TeV/c^{2} (1%)"
      color: [*gray, 3] 
      fill: False
      line: 1    
    - name: zp1000w10
      inputs: [MC.ZP1000w10]
      legend: !!str "Z' 1.0 TeV/c^{2} (1%)"
      color: [*gray, 3] 
      fill: False
      line: 1
    - name: zp1250w12p5
      inputs: [MC.ZP1250w12p5]
      legend: !!str "Z' 1.25 TeV/c^{2} (1%)"
      color: [*gray, 3] 
      fill: False
      line: 2
    - name: zp1500w15
      inputs: [MC.ZP1500w15]
      legend: !!str "Z' 1.5 TeV/c^{2} (1%)"
      color: [*gray, 3] 
      fill: False
      line: 3
    - name: zp2000w20
      inputs: [MC.ZP2000w20]
      legend: !!str "Z' 2.0 TeV/c^{2} (1%)"
      color: [*gray, 3]
      fill: False
      line: 4
    - name: zp3000w30
      inputs: [MC.ZP3000w30]
      legend: !!str "Z' 3.0 TeV/c^{2} (1%)"
      color: [*gray, 3]
      fill: False
      line: 5
    - name: zp4000w40
      inputs: [MC.ZP4000w40]
      legend: !!str "Z' 4.0 TeV/c^{2} (1%)"
      color: [*gray, 3]
      fill: False
      line: 6
    - name: zp500w50
      inputs: [MC.ZP500w50]
      legend: !!str "Z' 0.50 TeV/c^{2} (10%)"
      color: [*gray, 3]
      fill: False
      line: 1
    - name: zp750w75
      inputs: [MC.ZP750w75]
      legend: !!str "Z' 0.75 TeV/c^{2} (10%)"
      color: [*gray, 3] 
      fill: False
      line: 1
    - name: zp1000w100
      inputs: [MC.ZP1000w100]
      legend: !!str "Z' 1.0 TeV/c^{2} (10%)"
      color: [*gray, 3] 
      fill: False
      line: 1
    - name: zp1250w125
      inputs: [MC.ZP1250w125]
      legend: !!str "Z' 1.25 TeV/c^{2} (10%)"
      color: [*gray, 3] 
      fill: False
      line: 2
    - name: zp1500w150
      inputs: [MC.ZP1500w150]
      legend: !!str "Z' 1.5 TeV/c^{2} (10%)"
      color: [*gray, 3] 
      fill: False
      line: 3
    - name: zp2000w200
      inputs: [MC.ZP2000w200]
      legend: !!str "Z' 2.0 TeV/c^{2} (10%)"
      color: [*gray, 3]
      fill: False
      line: 4
    - name: zp3000w300
      inputs: [MC.ZP3000w300]
      legend: !!str "Z' 3.0 TeV/c^{2} (10%)"
      color: [*gray, 3]
      fill: False
      line: 5
    - name: zp4000w400
      inputs: [MC.ZP4000w400]
      legend: !!str "Z' 4.0 TeV/c^{2} (10%)"
      color: [*gray, 3]
      fill: False
      line: 6
    - name: rsg1000
      inputs: [MC.RSG1000]
      legend: !!str "Z' 1.0 TeV/c^{2} (RSG)"
      color: [*gray, 3]
      fill: False
      line: 1
    - name: rsg1500
      inputs: [MC.RSG1500]
      legend: !!str "Z' 1.5 TeV/c^{2} (RSG)"
      color: [*gray, 3]
      fill: False
      line: 2
    - name: rsg2000
      inputs: [MC.RSG2000]
      legend: !!str "Z' 2.0 TeV/c^{2} (RSG)"
      color: [*gray, 3]
      fill: False
      line: 3
    - name: rsg3000
      inputs: [MC.RSG3000]
      legend: !!str "Z' 3.0 TeV/c^{2} (RSG)"
      color: [*gray, 3]
      fill: False
      line: 4
    - name: rsg3500
      inputs: [MC.RSG3500]
      legend: !!str "Z' 3.5 TeV/c^{2} (RSG)"
      color: [*gray, 3]
      fill: False
      line: 5
    - name: rsg4000
      inputs: [MC.RSG4000]
      legend: !!str "Z' 4.0 TeV/c^{2} (RSG)"
      color: [*gray, 3]
      fill: False
      line: 6
    # Data channels
    #
    - name: data
      inputs: [DATA.DATA]
      legend: !!str "CMS Data 2012"
      color: [*black, 0] 
      fill: False
      line: null
    - name: data_qcd
      inputs: [DATA.QCD]
      legend: !!str "QCD data-driven"
      color: [*yellow, 1]
      fill: True
      line: null
    - name: bkgs
      inputs: [MC.W1Jets, MC.W2Jets, MC.W3Jets, MC.W4Jets, MC.DYJets_10to50, MC.DY1Jets_50toInf, MC.DY2Jets_50toInf, MC.DY3Jets_50toInf, MC.DY4Jets_50toInf, MC.SingleTop_T_sch, MC.SingleTop_T_tch, MC.SingleTop_T_tWch, MC.SingleTop_Tbar_sch, MC.SingleTop_Tbar_tch, MC.SingleTop_Tbar_tWch, MC.WW, MC.ZZ]
      legend: !!str "Background"
      color: [*green, -3]
      fill: True
      line: null
# Channel order in plots: all other channels not included here will be added
# to the bottom of the list. Abbreviations are NOT accepted
#
order:
    - bkgs
    - wlight
    - wc
    - wb
    - zjets
    - stop
    - diboson
    - ttbar
    - qcd
    - zp500w5
    - zp750w7p5
    - zp1000w10
    - zp1500w15
    - zp2000w20
    - zp3000w30
    - zp4000w40
    - zp500w50
    - zp750w75
    - zp1000w100
    - zp1500w150
    - zp2000w200
    - zp3000w300
    - zp4000w400
    - rsg1000
    - rsg1500
    - rsg2000
    - rsg3000
    - rsg3500
    - rsg4000
    - data

expand:
   # mc: !!str '^(ttbar|wjets|stop|zjets|diboson|bkgs)$'
   mc: !!str '^(ttbar|wlight|wc|wb|stop|zjets|diboson)$'
   zp1p: !!str '^(zp1000w10|zp1500w15|zp2000w20|zp3000w30)$'
   zp10p: !!str '^(zp1000w100|zp1500w150|zp2000w200|zp3000w300)$'
   rsg: !!str '^(rsg1000|rsg1500|rsg2000|rsg3000|rsg3500)'
   zp1pfull: !!str '^(zp500w5|zp750w7p5|zp1000w10|zp1250w12p5|zp1500w15|zp2000w20|zp3000w30|zp4000w40)$'
   zp10pfull: !!str '^(zp500w50|zp750w75|zp1000w100|zp1250w125|zp1500w150|zp2000w200|zp3000w300|zp4000w400)$'
   rsgfull: !!str '^(rsg1000|rsg1500|rsg2000|rsg3000|rsg3500|rsg4000)'
